replicaCount: 2

image:
  repository: caramingo/auth_node_app
  tag: "1.6.30"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 3000
  nodePort: 30003  # Можно выбрать любой свободный порт от 30000 до 32767

resources: {}

nodeSelector:
  node-type: worker
